### ISSUE TITLE
Integrate Phar classifier in dataset creation 

### ISSUE THREAD

**Issue by ladaapp** [ladaapp/lada#5]
Could be worth a shot to integrate [Phar](https://github.com/rlleshi/phar) in the mosaic restoration dataset creation pipeline.
It could be useful to create a more balanced dataset for the generic model or to create other specialized datasets for fine-tuning.
I haven't tried this project yet but looks promising.

**Comment by wheezy1749** [comment]
I've messed around with phar and in my opinion its not worth the processing power. Maybe the audio model portion could be helpful since its not so heavy. But the rest of it is pretty resource intense and its existing models are confused by mosaics from what I've seen.

Audio models are pretty simple to train though and pre-determing the best model for a given "scene type" would probably be the most efficient way to try to go about that route.

**Comment by ladaapp** [comment]
Interesting, thanks for the feedback.
If it's that resource-intensive then it's probably not worth the effort to look further.
Mosaics wouldn't be an issue as I'd have used this only in the dataset creation step (which uses western/non-mosaic video sources).
The intend was to tag each scene clip to detect and correct some bias in the training data e.g. if some scenes show up way more often or filter for specific scenes and create a specialized dataset for fine-tuning.
But if it's that slow then I wouldn't bother to integrate it.

(It also should be relatively accurate so one wouldn't need to spent time to manually adjust predictions afterwards)
