### ISSUE TITLE
Deep Mosaic / lada model interoperability

### ISSUE THREAD

**Issue by seatv** [ladaapp/lada#8]
Can one use you models with Depp Mosaic and vice versa?

**Comment by ladaapp** [comment]
You can use DeepMosaics within this project. The other way around is not possible.

Download their `clean_youknow_video.pth` model and put it into the folder `model_weights/3rd_party`.

Then you can run it from the CLI like so
```shell
lada-cli --input my-file --output my-file.restored.mp4 --mosaic-restoration-model deepmosaics --mosaic-restoration-model-path model_weights/3rd_party/clean_youknow_video.pth
```
In the GUI it can be selected in the side-panel if its available in that folder/path.

It's not included in the flatpak from flathub though as I didn't find a way to download still from google drive without API keys. No idea why they didn't upload it as a public release artifact on github :shrug: 
`https://github.com/flathub/io.github.ladaapp.lada/blob/master/io.github.ladaapp.lada.yaml`

**Comment by ladaapp** [comment]
Tesla K80 does support CUDA.
Not sure why ffmpeg matters here, do you want to use GPU hardware decoder/encoder via ffmpeg nvdec/nvenc?

**Comment by ladaapp** [comment]
Ah okay, I see.
Currently no hardware encoders/decoders are used. I did a quick test some time ago to use nvenc instead of libx264/libx265 but didn't notice much of a difference on my hardware. Probably because GPU was fully busy running the restoration task. But I also have a relatively capable CPU so running encoding on CPU wasn't the bottleneck and put some pressure off the GPU. Maybe on different hardware its worth though.
Good luck with setting up your K80 then. Hope it still has some life left in it after all that crypto mining it probably had to endure :smile:

**Comment by seatv** [comment]
Here is the link: https://www.newegg.com/mr/05067C85B485656AA8F12AE834F72EE5/09804CA71DE2369E410AF0357185B5A5FCBEB4E9C2D6EBC00937853DA28BE614123EAC5A2707DA96A783616A292D102A58219A50273DB5E701A8E28162BD4BFB27F676E5638454ABDECDBFCCE77D121FF13458AF391995937E98987E0CA05461F3597617D46BE72C13351CDF7DBDA7235DA7F3FC05B340BC8B097ED19B583D5C116BE15DBCBB230755B6A890DBEB1CEE4EC1BEE43C411E07813A05D66735E21B05CE8DBB2ABF500FC1EAD0AE4CF7B1E9BCEB7B1B820DA7E8AE78C3D41106255AB47DDC3901FD0D8C54B5763503A3BEBF6B64FBD4276571C123450C9E70D43875287D95782460EEA7F1F3D4D79B57F55B

Hopefully, I will get the thing to work. I know I can spend a few more dollars and get a graphics card that is plug and play; but it is winter, so decided have some indoor fun, LOL.
